### ISSUE TITLE
希望添加来源声明

### ISSUE THREAD

**Issue by timandy** [go-eden/routine#12]
看了最新版本源码，其中 goid 获取方式基本参考了我的 [gohack](https://www.github.com/timandy/gohack) 项目。希望作者能声明下来源和地址，谢谢！

**Comment by sisyphsu** [comment]
我在文档中增加了鸣谢章节，说明了`internal/g`模块的代码来源，请查看。

不过我确实没有注意到你的`gohack`项目，而是在查看forks变更时，发现你的[routine](https://github.com/timandy/routine)版本中增加的`g0`对于偏移量计算很有帮助，新版store的垃圾回收机制也受到了`labels`相关逻辑的启发。
