### ISSUE TITLE
Func getGoidByNative

### ISSUE THREAD

**Issue by bugaolengdeyuxiaoer** [go-eden/routine#4]
Env:mac Darwin Kernel Version 20.4.0 arm64
Problem :
![image](https://user-images.githubusercontent.com/46627662/144804380-15c81833-905c-4866-a35b-ee9f664b98a2.png)

Compare p equals to nil is necessary?
pr: https://github.com/go-eden/routine/pull/5

**Comment by sisyphsu** [comment]
It looks necessary.

Maybe there has something unexpected happens in arm64, i'll try to fix it.

**Comment by sisyphsu** [comment]
Your pr has been merged, check it in `v0.0.2` version~
