### ISSUE TITLE
一般什么条件下会调用 getGoidByStack 从堆栈中获取 goid？

### ISSUE THREAD

**Issue by cjphaha** [go-eden/routine#6]
大佬您好，获取 goid 的降级有什么条件吗？

**Comment by sisyphsu** [comment]
1. golang版本过低，现在一般都不会用那么旧的版本
2. golang版本过高，没来得及升级的话，会默认降级为getGoidByStack

**Comment by cjphaha** [comment]
抱歉刚看到大佬留言，谢谢！
