### ISSUE TITLE
getAllGoidByNative中是否不应该过滤gDead

### ISSUE THREAD

**Issue by manchurio** [go-eden/routine#7]
```go
if runtimeReadgstatus(gp) == gDead || runtimeIsSystemGoroutine(gp, false) {
    continue
}
```
在系统调用/cgo/新建g的时候, g的状态也是gDead, 是否不应该在这里过滤掉gDead状态的g
因为这里的g状态虽然是dead,但等一会还是会恢复成runnable
如[cgo调用](https://github.com/golang/go/blob/41d8e61a6b9d8f9db912626eb2bbc535e929fefc/src/runtime/proc.go#L1897)

**Comment by sisyphsu** [comment]
此处逻辑参考了`runtime.Stack`的内部实现。

`gDead`表示协程`just exited`或`just being initialized`，它此时没有独立的stack，不被视为有效的协程。
