### ISSUE TITLE
请问支持go1.18了吗？

### ISSUE THREAD

**Issue by ikechan8370** [go-eden/routine#8]
1.18下好像不能用了，请问开发者有支持1.18的计划吗

**Comment by sisyphsu** [comment]
很抱歉，短期内支持不了。

1.18对runtime的访问增加了限制，暂时还没有找到解法。

**Comment by ikechan8370** [comment]
好吧，大佬加油，我先暂时停留在1.17好了。

**Comment by manchurio** [comment]
改一下 linkname就可以, 现在用1.18 没有问题

**Comment by czegi90** [comment]
我们期待这项工作得以实施。 不幸的是，这目前阻止了我们的项目使用 go 1.18。

**Comment by lvyahui8** [comment]
> linkname

请问linkname是怎么修改的呀？

**Comment by lvyahui8** [comment]
> 改一下 linkname就可以, 现在用1.18 没有问题

@manchurio 请问linkname应该怎么修改呀？

**Comment by sisyphsu** [comment]
很抱歉拖了这么久。

我已经找到了一种比较可靠的go1.18兼容方案，未来一周内应该会发布新版本。

**Comment by sisyphsu** [comment]
@ikechan8370 @manchurio @lvyahui8 

支持`go1.18`的新版本`v1.0.0`已经发布，访问go-routine相关逻辑，使用更优雅的方案重写了一遍，Goid、LocalStorage相关的性能也有部分提升，欢迎使用。
