### ISSUE TITLE
请问支持go1.17 arm64架构吗

### ISSUE THREAD

**Issue by markma-crypto** [go-eden/routine#9]
使用的时候报错如下：
goroutine 1 [running, locked to thread]:
runtime.throw({0x10226d3d6, 0x5})
        /usr/local/go/src/runtime/panic.go:1198 +0x54 fp=0x14000068c60 sp=0x14000068c30 pc=0x10220db94
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:742 +0x1e4 fp=0x14000068ca0 sp=0x14000068c60 pc=0x102223e04
github.com/go-eden/routine.getGoidByNative()
        /Users/markma/go/pkg/mod/github.com/go-eden/routine@v0.0.3/routine_goid.go:75 +0x48 fp=0x14000068cd0 sp=0x14000068cb0 pc=0x10226c1f8
github.com/go-eden/routine.Goid()
        /Users/markma/go/pkg/mod/github.com/go-eden/routine@v0.0.3/routine_api.go:69 +0x20 fp=0x14000068cf0 sp=0x14000068cd0 pc=0x10226bec0
github.com/go-eden/routine.loadCurrentStore()
        /Users/markma/go/pkg/mod/github.com/go-eden/routine@v0.0.3/routine_storage.go:77 +0x20 fp=0x14000068dd0 sp=0x14000068cf0 pc=0x10226c720
github.com/go-eden/routine.(*storage).Clear(...)
        /Users/markma/go/pkg/mod/github.com/go-eden/routine@v0.0.3/routine_storage.go:70
github.com/go-eden/routine.NewLocalStorage()
        /Users/markma/go/pkg/mod/github.com/go-eden/routine@v0.0.3/routine_api.go:60 +0x24 fp=0x14000068df0 sp=0x14000068dd0 pc=0x10226be24
main.init()
        /Users/markma/GolandProjects/awesomeProject/main.go:8 +0x20 fp=0x14000068e10 sp=0x14000068df0 pc=0x10226ce20
runtime.doInit(0x102305aa0)
        /usr/local/go/src/runtime/proc.go:6498 +0x138 fp=0x14000068f70 sp=0x14000068e10 pc=0x10221edb8
runtime.main()
        /usr/local/go/src/runtime/proc.go:238 +0x22c fp=0x14000068fd0 sp=0x14000068f70 pc=0x10221032c
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm64.s:1133 +0x4 fp=0x14000068fd0 sp=0x14000068fd0 pc=0x10223b924

go env 如下
GO111MODULE="on"
GOARCH="arm64"
GOBIN="/usr/local/go/bin"
GOCACHE="/Users/markma/Library/Caches/go-build"
GOENV="/Users/markma/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/markma/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/markma/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.17.1"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/markma/GolandProjects/awesomeProject/go.mod"

**Comment by sisyphsu** [comment]
新版本`v1.0.0`支持`arm64`架构，有问题请再反馈，谢谢~
